VIA_ENABLE = yes
VIAL_ENABLE = yes

#ENCODER_ENABLE = yes   编码器的支持

VIALRGB_ENABLE = yes
 
#RGB_MATRIX_DRIVER = WS2812
#RGB_MATRIX_CUSTOM_KB = yes
#RADIAL_CONTROLLER_ENABLE = yes
#RGB_MATRIX_CONTROL_ENABLE = yes
#UNDERGLOW_RGB_MATRIX_ENABLE = yes
#OPENRGB_ENABLE = yes
#VIA_CUSTOM_KEYCODE_ENABLE = yes
#KEYBOARD_SHARED_EP = yes
#RGB_INDICATORS_ENABLE = yes
#RGB_INDICATORS = dynamic
#VIAL_ENABLE = yes
#VIAL_INSECURE = yes
#VIAL_ENCODERS_ENABLE = no
#VIALRGB_ENABLE = yes
#QMK_SETTINGS = yes