#pragma once

#define AUDIO_PIN A8
#define AUDIO_PWM_DRIVER PWMD1
#define AUDIO_PWM_CHANNEL 1
#define AUDIO_CLICKY
#define AUDIO_INIT_DELAY
#define AUDIO_CLICKY_FREQ_DEFAULT 2000.0f
#define AUDIO_CLICKY_FREQ_MIN 500.0f
#define AUDIO_CLICKY_FREQ_MAX 4000.0f

#define SOLENOID_PIN C9
#define SOLENOID_DWELL_STEP_SIZE 5
#define HAPTIC_OFF_IN_LOW_POWER 1

#define WS2812_PWM_DRIVER PWMD2
#define WS2812_PWM_CHANNEL 4
#define WS2812_DMA_STREAM STM32_DMA1_STREAM2
#define WS2812_DMA_CHANNEL 2
#define RGB_MATRIX_LED_COUNT 4
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
