#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
#define VIAL_KEYBOARD_UID {0x8E, 0xDE, 0x9B, 0xC2, 0xF3, 0x00, 0xC1, 0x9E}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 12 }
